### ISSUE TITLE
db:create permission issue

### ISSUE THREAD

**Issue by Baleplan** [instructure/rollcall-attendance#7]
Environment: Ubuntu Server 18.04
Docker: 18.06.1-ce, build e68fc7a
Docker Compose: version 1.22.0, build f46880fe

`docker-compose run --rm web bundle exec rake db:create` fails with a permission error.

```
Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/src/app/tmp
/home/docker/.gem/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/store.rb:73:in `dump_data'
/home/docker/.gem/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/store.rb:55:in `commit_transaction'
/home/docker/.gem/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/store.rb:47:in `transaction'
/home/docker/.gem/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/cache.rb:130:in `push_paths_locked'
/home/docker/.gem/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/cache.rb:113:in `block in reinitialize'
/home/docker/.gem/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/cache.rb:107:in `synchronize'
/home/docker/.gem/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/cache.rb:107:in `reinitialize'
/home/docker/.gem/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/cache.rb:14:in `initialize'
/home/docker/.gem/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache.rb:33:in `new'
/home/docker/.gem/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache.rb:33:in `setup'
/home/docker/.gem/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap.rb:24:in `setup'
/home/docker/.gem/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/setup.rb:33:in `<top (required)>'
/usr/src/app/config/boot.rb:22:in `require'
/usr/src/app/config/boot.rb:22:in `<top (required)>'
/usr/src/app/config/application.rb:18:in `require'
/usr/src/app/config/application.rb:18:in `<top (required)>'
/usr/src/app/Rakefile:22:in `require'
/usr/src/app/Rakefile:22:in `<top (required)>'
/home/docker/.gem/ruby/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
```

**Comment by phamr39** [comment]
I added ```user: root``` in the services/web filed docker-compose.yml file. It's worked for me but I met this issue when execute ```docker-compose run --rm web bundle exec rake db:migrate``` command.
